services:
  db:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: Tech@#123
      MYSQL_DATABASE: userauthentication
      MYSQL_USER: root
      MYSQL_PASSWORD: Tech@#123
    ports:
      - "3307:3306"

  app:
    build: .
    container_name: user-authentication-project
    environment:
      DB_URL: jdbc:mysql://db:3306/userauthentication
      DB_USERNAME: root
      DB_PASSWORD: Tech@#123
    depends_on:
      - db
    ports:
      - "8080:8080"
